AWS_ACCESS_KEY: "AKIATM4STKUWXZJXB65F"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "flixster-devinanderson"
AWS_REGION: "us-east-1"
SECRET_KEY: 'sk_test_ayC9jlxHI3tl1Zi59tlGgFj100ywoluxvd'
PUBLISHABLE_KEY: 'pk_test_9YEvUPiOui0VZPvzc938Qbg000SFoXe4j6'